name: yon_quiz
description: A Flutter Clean Architecture project with GetX

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.9.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.1
  uuid: ^4.5.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
